import { useState, useEffect } from 'react';
import { useSearchParams, useNavigate, Link } from 'react-router-dom';
import { AlertCircle, CheckCircle, ImagePlus, Send, Info } from 'lucide-react';
import { createLostPost, createFoundPost, suggestQuestions, generateDescription, getPostDetail } from '../../services/postService';
import { useAuth } from '../../hooks/useAuth';
import PostDetailModal from '../../components/post/PostDetailModal';

const HCMC_DISTRICTS = [
  "Quận 1", "Quận 3", "Quận 4", "Quận 5", "Quận 6", "Quận 7", "Quận 8", "Quận 10", "Quận 11", "Quận 12",
  "Quận Bình Thạnh", "Quận Bình Tân", "Quận Gò Vấp", "Quận Phú Nhuận", "Quận Tân Bình", "Quận Tân Phú",
  "Thành phố Thủ Đức", "Huyện Bình Chánh", "Huyện Cần Giờ", "Huyện Củ Chi", "Huyện Hóc Môn", "Huyện Nhà Bè"
];

const matchDistrict = (extracted) => {
    if (!extracted) return '';
    const cleanExtracted = extracted.toLowerCase().replace(/huyện|quận|thành phố|tp\.|tp/g, '').trim();
    
    // Map old districts after merger to "Thành phố Thủ Đức"
    if (cleanExtracted === '2' || cleanExtracted === '9' || cleanExtracted === 'thủ đức') {
        return 'Thành phố Thủ Đức';
    }

    const matched = HCMC_DISTRICTS.find(d => {
        const cleanD = d.toLowerCase().replace(/huyện|quận|thành phố|tp\.|tp/g, '').trim();
        return cleanD === cleanExtracted || cleanExtracted.includes(cleanD) || cleanD.includes(cleanExtracted);
    });
    return matched || '';
};

export default function CreatePost() {
    const [searchParams, setSearchParams] = useSearchParams();
    const navigate = useNavigate();
    const { user } = useAuth();
    const modeParam = searchParams.get('mode');
    const mode = (modeParam === 'found' || modeParam === 'lost') ? modeParam : 'lost';

    const setMode = (newMode) => {
        setSearchParams({ mode: newMode });
    };

    const [notification, setNotification] = useState(null);
    const [locationQuery, setLocationQuery] = useState('');
    const [suggestions, setSuggestions] = useState([]);
    const [selectedLocation, setSelectedLocation] = useState({
        address: '',
        district: '',
        latitude: null,
        longitude: null,
        locationLevel: null
    });
    const [typingTimeout, setTypingTimeout] = useState(null);

    const [currentStep, setCurrentStep] = useState(1);
    const [suggestedQuestions, setSuggestedQuestions] = useState([]);
    const [verificationsList, setVerificationsList] = useState([]);
    const [isGeneratingQuestions, setIsGeneratingQuestions] = useState(false);
    const [submitClicked, setSubmitClicked] = useState(false);
    const [matchesList, setMatchesList] = useState([]);
    const [fetchedMatchDetails, setFetchedMatchDetails] = useState({});
    const [isMatchesModalOpen, setIsMatchesModalOpen] = useState(false);
    const [isGeneratingDescription, setIsGeneratingDescription] = useState(false);
    const [selectedPostId, setSelectedPostId] = useState(null);
    const [selectedDistrict, setSelectedDistrict] = useState('');

    const handleAutoGenerateDescription = async () => {
        if (images.length === 0) return;
        setIsGeneratingDescription(true);
        setNotification({ message: 'AI đang tiến hành tạo mô tả từ hình ảnh...', type: 'info' });
        try {
            const response = await generateDescription(images[0]);
            const genData = response?.data;
            if (genData && genData.description) {
                const descText = genData.description;
                const tagsList = genData.tags || [];
                const tagsStr = tagsList.map(tag => `#${tag}`).join(' ');
                const finalDesc = tagsStr ? `${descText}\n\n${tagsStr}` : descText;

                setFormData(prev => ({
                    ...prev,
                    description: finalDesc
                }));
                setNotification({ message: 'Tạo mô tả thành công!', type: 'success' });
                setTimeout(() => setNotification(null), 2000);
            } else {
                throw new Error("Không nhận được mô tả từ server");
            }
        } catch (error) {
            console.error("Lỗi khi tự động tạo mô tả:", error);
            setNotification({ message: 'Tạo mô tả tự động thất bại. Vui lòng tự nhập!', type: 'error' });
            setTimeout(() => setNotification(null), 4000);
        } finally {
            setIsGeneratingDescription(false);
        }
    };

    useEffect(() => {
        if (suggestedQuestions && suggestedQuestions.length > 0) {
            setVerificationsList(
                suggestedQuestions.map(q => ({
                    title: q.title || q.question || '',
                    correctAnswer: q.correctAnswer || q.answer || '',
                    importantPoint: q.importantPoint !== undefined ? q.importantPoint : (q.important_point !== undefined ? q.important_point : 1)
                }))
            );
        }
    }, [suggestedQuestions]);

    useEffect(() => {
        if (submitClicked && !isGeneratingQuestions) {
            setNotification(null);
            setCurrentStep(2);
            setSubmitClicked(false);
        }
    }, [isGeneratingQuestions, submitClicked]);

    useEffect(() => {
        if (isMatchesModalOpen && matchesList.length > 0) {
            matchesList.forEach(async (match) => {
                if (fetchedMatchDetails[match.post_id]) return;
                try {
                    const response = await getPostDetail(match.post_id);
                    const postInfo = response?.data || response;
                    if (postInfo) {
                        setFetchedMatchDetails(prev => ({
                            ...prev,
                            [match.post_id]: postInfo
                        }));
                    }
                } catch (err) {
                    console.error("Lỗi khi tải thông tin chi tiết bài viết tương đồng:", err);
                }
            });
        }
    }, [isMatchesModalOpen, matchesList]);

  const [formData, setFormData] = useState({
    title: '',
    description: '',
      eventTime: '',
    location: '',
    dateTime: '',
    name: '',
    phone: '',
    visibility: 'public',
  });

  const [images, setImages] = useState([]);
  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: value
    }));
  };

  const handleLocationChange = (e) => {
    const value = e.target.value;
    setLocationQuery(value);

    if (typingTimeout) clearTimeout(typingTimeout);

    if (value.trim().length < 3) {
      setSuggestions([]);
      return;
    }

    setTypingTimeout(
      setTimeout(async () => {
        try {
          const url = `https://nominatim.openstreetmap.org/search?q=${encodeURIComponent(value)}&format=json&addressdetails=1&limit=5&countrycodes=vn&viewbox=106.35,11.16,107.03,10.35&bounded=1`;
          const response = await fetch(url, {
            headers: {
              'Accept-Language': 'vi',
              'User-Agent': 'SaigonTimDoDemoApp/1.0'
            }
          });
          const data = await response.json();
          setSuggestions(data);
        } catch (error) {
          console.error("Lỗi khi tìm kiếm địa chỉ:", error);
        }
      }, 300)
    );
  };

  const handleSelectSuggestion = (item) => {
    const addressDetails = item.address || {};
    const district = addressDetails.city_district || addressDetails.county || addressDetails.suburb || "";
    
    const hasDetail = !!(addressDetails.road || addressDetails.house_number || addressDetails.building || addressDetails.amenity || addressDetails.shop || addressDetails.tourism || addressDetails.leisure || addressDetails.highway);
    
    let level = 1;
    if (!hasDetail && addressDetails.suburb) {
      level = 8;
    }
    
    setSelectedLocation({
      address: item.display_name,
      district: district,
      latitude: parseFloat(item.lat),
      longitude: parseFloat(item.lon),
      locationLevel: level
    });
    
    setLocationQuery(item.display_name);

    // Auto extract and match the district from Nominatim suggestions
    const matched = matchDistrict(district);
    if (matched) {
      setSelectedDistrict(matched);
    } else if (district) {
      const cleaned = district.toLowerCase();
      const found = HCMC_DISTRICTS.find(d => cleaned.includes(d.toLowerCase().replace(/huyện|quận|thành phố|tp\.|tp/g, '').trim()));
      if (found) {
        setSelectedDistrict(found);
      }
    }
    setSuggestions([]);
  };

  const triggerSuggestQuestions = async (imageFile) => {
    try {
      setIsGeneratingQuestions(true);
      const questions = await suggestQuestions(formData.description, imageFile);
      
      let qList = [];
      if (questions && questions.data && Array.isArray(questions.data.questions)) {
        qList = questions.data.questions;
      } else if (Array.isArray(questions)) {
        qList = questions;
      } else if (questions && Array.isArray(questions.questions)) {
        qList = questions.questions;
      }
      
      setSuggestedQuestions(qList);
      setIsGeneratingQuestions(false);
    } catch (error) {
      console.error("Lỗi khi gợi ý câu hỏi:", error);
      setIsGeneratingQuestions(false);
    }
  };

  const handleImageUpload = (e) => {
    const files = Array.from(e.target.files);
    if (files.length === 0) return;
    
    const file = files[0];
    setImages([file]);

    if (mode === 'found') {
      triggerSuggestQuestions(file);
    }
  };

  const removeImage = (index) => {
    setImages(prev => prev.filter((_, i) => i !== index));
  };

  const handleAddQuestion = () => {
    setVerificationsList(prev => [
      ...prev,
      { title: '', correctAnswer: '', importantPoint: 1 }
    ]);
  };

  const handleRemoveQuestion = (index) => {
    setVerificationsList(prev => prev.filter((_, i) => i !== index));
  };

  const handleQuestionChange = (index, field, value) => {
    setVerificationsList(prev => prev.map((q, i) => {
      if (i === index) {
        return {
          ...q,
          [field]: field === 'importantPoint' ? parseInt(value) || 0 : value
        };
      }
      return q;
    }));
  };

    const handleSubmit = async (e) => {
        e.preventDefault();

        // Image validation in found mode (mandatory)
        if (mode === 'found' && images.length === 0) {
            setNotification({ message: 'Hình ảnh là bắt buộc đối với tin đăng tìm thấy!', type: 'error' });
            setTimeout(() => setNotification(null), 3000);
            return;
        }

        // District validation in found mode (mandatory)
        if (mode === 'found' && !selectedDistrict) {
            setNotification({ message: 'Vui lòng chọn Quận/Huyện!', type: 'error' });
            setTimeout(() => setNotification(null), 3000);
            return;
        }

        // If in found mode and on step 1, transition to step 2 first
        if (mode === 'found' && currentStep === 1) {
            if (isGeneratingQuestions) {
                setSubmitClicked(true);
                setNotification({ message: 'Hệ thống đang sinh câu hỏi, vui lòng chờ trong giây lát...', type: 'info' });
                return;
            }
            setCurrentStep(2);
            return;
        }

        // Validation for step 2 in found mode
        if (mode === 'found' && currentStep === 2) {
            if (verificationsList.length === 0) {
                setNotification({ message: 'Vui lòng thêm ít nhất 1 câu hỏi xác minh!', type: 'error' });
                setTimeout(() => setNotification(null), 3000);
                return;
            }
            const hasEmpty = verificationsList.some(q => !q.title.trim() || !q.correctAnswer.trim());
            if (hasEmpty) {
                setNotification({ message: 'Vui lòng điền đầy đủ câu hỏi và đáp án!', type: 'error' });
                setTimeout(() => setNotification(null), 3000);
                return;
            }
        }

        try {
            const hasCoords = !!selectedLocation.latitude;
            const finalLat = hasCoords ? selectedLocation.latitude : 10.7769;
            const finalLon = hasCoords ? selectedLocation.longitude : 106.7009;
            const finalAddress = hasCoords ? selectedLocation.address : (locationQuery || 'Thành phố Hồ Chí Minh');
            const finalDistrict = selectedDistrict;

            let customQuestionsJson = undefined;
            if (mode === 'found') {
                const mappedQuestions = verificationsList.map(v => ({
                    question: v.title,
                    type: "TEXT",
                    options: [],
                    answer: v.correctAnswer,
                    important_point: Number(v.importantPoint) || 1
                }));
                customQuestionsJson = JSON.stringify(mappedQuestions);
            }

            const postData = {
                title: formData.title,
                description: formData.description || null,
                eventTime: formData.dateTime ? new Date(formData.dateTime).toISOString() : null,
                userId: user ? (user.userId || user.id) : undefined,
                hidePostType: mode === 'found' && formData.visibility === 'match' ? 'WHEN_MATCH' : 'PUBLIC',
                address: finalAddress,
                district: finalDistrict,
                city: 'Thành phố Hồ Chí Minh',
                latitude: finalLat,
                longitude: finalLon,
                locationLevel: 0, // Always send 0 as requested
                image: images.length > 0 ? images[0] : null,
                phone: user ? user.phone : formData.phone,
                name: user ? user.name : formData.name,
                customQuestionsJson: customQuestionsJson
            };
            setNotification({ message: 'Đang tiến hành đăng tin...', type: 'info' });
            const result = mode === 'found'
                ? await createFoundPost(postData)
                : await createLostPost(postData);
            
            console.log("Kết quả từ server:", result);

            const matches = result?.matches || result?.data?.matches || result?.match || [];
            if (matches && matches.length > 0) {
                setNotification({ message: 'Đăng tin thành công! Đang đối chiếu các tin tương đồng...', type: 'success' });
                setTimeout(() => {
                    setNotification(null);
                    setMatchesList(matches);
                    setIsMatchesModalOpen(true);
                }, 1500);
            } else {
                setNotification({ message: 'Đăng tin thành công!', type: 'success' });
                setTimeout(() => {
                    setNotification(null);
                    navigate('/');
                }, 2000);
            }
        } catch (error) {
            console.error("Lỗi khi đăng tin:", error);
            setNotification({ message: 'Đăng tin thất bại. Vui lòng kiểm tra lại kết nối hoặc dữ liệu!', type: 'error' });
            setTimeout(() => {
                setNotification(null);
            }, 4000);
        }
    };

  return (
    <main className="max-w-[800px] mx-auto px-4 md:px-0 py-8 min-h-screen relative">
      {/* Toast Notification */}
      {notification && (
        <div className="fixed top-24 right-6 z-[9999] transition-all duration-300 animate-bounce">
          <div className={`flex items-center gap-3 px-6 py-3.5 rounded-xl shadow-lg border ${
            notification.type === 'success' 
              ? 'bg-green-50 border-green-200 text-green-800' 
              : notification.type === 'error'
              ? 'bg-red-50 border-red-200 text-red-800'
              : 'bg-blue-50 border-blue-200 text-blue-800'
          }`}>
            {notification.type === 'success' && <CheckCircle size={20} className="text-green-600" />}
            {notification.type === 'error' && <AlertCircle size={20} className="text-red-600" />}
            {notification.type === 'info' && <Info size={20} className="text-blue-600 animate-spin" />}
            <span className="font-semibold font-body-md">{notification.message}</span>
          </div>
        </div>
      )}
      {/* Header */}
      <div className="mb-8 text-center">
        <h1 className="text-3xl md:text-4xl font-bold mb-2 text-primary">Đăng tin mới</h1>
        <p className="text-on-surface-variant text-base md:text-lg">
          Chia sẻ thông tin để cộng đồng cùng hỗ trợ bạn.
        </p>
      </div>

      {/* Form Card */}
      <div className="form-card bg-surface-container-lowest rounded-xl p-8 border border-outline-variant/30 shadow-sm">

        {/* Toggle Selector */}
        <div className="flex p-1 bg-surface-container rounded-xl mb-6">
          <button
            onClick={() => setMode('lost')}
            className={`toggle-btn flex-1 py-3 rounded-lg font-headline-md text-center transition-all duration-300 flex items-center justify-center gap-2 ${
              mode === 'lost' 
                ? 'active bg-primary text-white' 
                : 'text-on-surface-variant hover:bg-surface-container-high'
            }`}
          >
            <AlertCircle size={20} />
            Báo mất đồ
          </button>
          <button
            onClick={() => setMode('found')}
            className={`toggle-btn flex-1 py-3 rounded-lg font-headline-md text-center transition-all duration-300 flex items-center justify-center gap-2 ${
              mode === 'found' 
                ? 'active bg-primary text-white' 
                : 'text-on-surface-variant hover:bg-surface-container-high'
            }`}
          >
            <CheckCircle size={20} />
            Báo tìm thấy đồ
          </button>
        </div>

        {/* Form */}
        <form onSubmit={handleSubmit} className="space-y-6">

          {currentStep === 1 ? (
            <>
              {/* Title */}
              <div className="space-y-1">
                <label className="font-label-bold text-label-bold text-on-surface-variant uppercase tracking-wider">
                  Tiêu đề <span className="text-red-500">*</span>
                </label>
                <input
                  type="text"
                  name="title"
                  value={formData.title}
                  onChange={handleInputChange}
                  className="w-full px-4 py-3 rounded-lg border border-outline-variant bg-surface font-body-lg transition-all focus:border-primary focus:ring-2 focus:ring-primary/10"
                  placeholder="Ví dụ: Mất ví màu nâu tại Quận 1"
                  required
                />
              </div>

              {/* Image Upload */}
              <div className="space-y-1">
                <label className="font-label-bold text-label-bold text-on-surface-variant uppercase tracking-wider">
                  Hình ảnh {mode === 'found' && <span className="text-red-500">*</span>}
                </label>
                <label className="border-2 border-dashed border-outline-variant rounded-xl p-8 flex flex-col items-center justify-center bg-surface-container-low hover:bg-surface-container-high transition-colors cursor-pointer group">
                  <ImagePlus size={48} className="text-primary mb-2 group-hover:scale-110 transition-transform" />
                  <p className="font-body-lg font-semibold">Nhấn để tải ảnh lên</p>
                  <input
                    type="file"
                    accept="image/*"
                    onChange={handleImageUpload}
                    className="hidden"
                  />
                </label>

                {/* Image Preview */}
                {images.length > 0 && (
                  <div className="grid grid-cols-3 md:grid-cols-5 gap-2 mt-4">
                    {images.map((image, index) => (
                      <div key={index} className="relative">
                        <img
                          src={URL.createObjectURL(image)}
                          alt={`Preview ${index}`}
                          className="w-full h-20 object-cover rounded-lg border border-outline-variant"
                        />
                        <button
                          type="button"
                          onClick={() => removeImage(index)}
                          className="absolute top-0 right-0 bg-red-500 text-white rounded-full p-1 -translate-y-1/2 translate-x-1/2 hover:bg-red-600 transition-all"
                        >
                          ×
                        </button>
                      </div>
                    ))}
                  </div>
                )}
              </div>

              {/* Description */}
              <div className="space-y-1">
                <div className="flex justify-between items-center">
                  <label className="font-label-bold text-label-bold text-on-surface-variant uppercase tracking-wider">
                    Mô tả chi tiết
                  </label>
                  {images.length > 0 && (
                    <button
                      type="button"
                      onClick={handleAutoGenerateDescription}
                      disabled={isGeneratingDescription}
                      className="px-3 py-1 bg-primary/10 hover:bg-primary/20 text-primary font-bold rounded-lg text-xs transition-all flex items-center gap-1.5 active:scale-95 disabled:opacity-50 disabled:pointer-events-none cursor-pointer"
                    >
                      <span className="material-symbols-outlined text-[14px]">auto_awesome</span>
                      {isGeneratingDescription ? 'Đang viết mô tả...' : 'Tự động tạo mô tả'}
                    </button>
                  )}
                </div>
                <textarea
                  name="description"
                  value={formData.description}
                  onChange={handleInputChange}
                  className="w-full px-4 py-3 rounded-lg border border-outline-variant bg-surface font-body-lg transition-all focus:border-primary focus:ring-2 focus:ring-primary/10"
                  placeholder="Mô tả đặc điểm nhận dạng, nhãn hiệu, các giấy tờ bên trong..."
                  rows="4"
                />
              </div>

              {/* Grid for Location & Time */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {/* Location Input with Autocomplete */}
                <div className="space-y-1 relative md:col-span-1">
                  <label className="font-label-bold text-label-bold text-on-surface-variant uppercase tracking-wider">
                    Vị trí chi tiết (Nhập để tìm kiếm) {mode === 'found' && <span className="text-red-500">*</span>}
                  </label>
                  <input
                    type="text"
                    value={locationQuery}
                    onChange={handleLocationChange}
                    placeholder="Nhập địa chỉ (ví dụ: 135 Nguyễn Huệ)..."
                    className="w-full px-4 py-3 rounded-lg border border-outline-variant bg-surface font-body-lg transition-all focus:border-primary focus:ring-2 focus:ring-primary/10"
                    required={mode === 'found'}
                  />
                  
                  {/* suggestions list */}
                  {suggestions.length > 0 && (
                    <ul className="absolute left-0 right-0 mt-1 bg-surface border border-outline-variant rounded-lg shadow-lg z-[999] max-h-60 overflow-y-auto">
                      {suggestions.map((item, index) => (
                        <li
                          key={index}
                          onClick={() => handleSelectSuggestion(item)}
                          className="px-4 py-3 hover:bg-surface-container-high cursor-pointer text-sm border-b border-outline-variant/30 last:border-b-0 flex items-center gap-2 text-on-surface"
                        >
                          <span className="material-symbols-outlined text-outline text-[18px]">location_on</span>
                          <span className="truncate">{item.display_name}</span>
                        </li>
                      ))}
                    </ul>
                  )}
                </div>

                {/* District Select Dropdown */}
                <div className="space-y-1 md:col-span-1">
                  <label className="font-label-bold text-label-bold text-on-surface-variant uppercase tracking-wider block">
                    Quận / Huyện {mode === 'found' && <span className="text-red-500">*</span>}
                  </label>
                  <select
                    value={selectedDistrict}
                    onChange={(e) => setSelectedDistrict(e.target.value)}
                    required={mode === 'found'}
                    className="w-full px-4 py-3 rounded-lg border border-outline-variant bg-surface font-body-lg cursor-pointer transition-all focus:border-primary focus:ring-2 focus:ring-primary/10"
                  >
                    <option value="">-- Chọn Quận/Huyện --</option>
                    {HCMC_DISTRICTS.map((d) => (
                      <option key={d} value={d}>
                        {d}
                      </option>
                    ))}
                  </select>
                </div>

                {/* Time */}
                <div className="space-y-1 md:col-span-2">
                  <label className="font-label-bold text-label-bold text-on-surface-variant uppercase tracking-wider">
                    Thời gian
                  </label>
                  <input
                    type="datetime-local"
                    name="dateTime"
                    value={formData.dateTime}
                    onChange={handleInputChange}
                    className="w-full px-4 py-3 rounded-lg border border-outline-variant bg-surface font-body-lg cursor-pointer transition-all focus:border-primary focus:ring-2 focus:ring-primary/10"
                  />
                </div>
              </div>

              {/* Remind logged-in user in Lost mode about public contact info */}
              {mode === 'lost' && user && (
                <div className="mt-4 flex items-start gap-3 p-4 bg-primary/5 rounded-xl border border-primary/10">
                  <Info size={20} className="text-primary flex-shrink-0 mt-0.5" />
                  <p className="font-body-sm text-on-surface">
                    Thông tin số điện thoại của bạn sẽ được công khai để người nhặt có thể liên hệ.
                  </p>
                </div>
              )}

              {/* Contact Information Section */}
              {(!user || mode === 'found') && (
                <div className="pt-6 border-t border-outline-variant/30 mt-6">
                  <label className="font-label-bold text-label-bold text-on-surface-variant uppercase tracking-wider block mb-4">
                    Thông tin liên hệ
                  </label>

                  {/* Lost Mode Contact Info */}
                  {mode === 'lost' && !user && (
                    <div>
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                        <div className="space-y-1">
                          <label className="font-label-bold text-label-bold text-on-surface-variant uppercase tracking-wider">
                            Họ và tên
                          </label>
                          <input
                            type="text"
                            name="name"
                            value={formData.name}
                            onChange={handleInputChange}
                            className="w-full px-4 py-3 rounded-lg border border-outline-variant bg-surface font-body-lg transition-all focus:border-primary focus:ring-2 focus:ring-primary/10"
                            placeholder="Ví dụ: Nguyễn Văn A"
                          />
                        </div>
                        <div className="space-y-1">
                          <label className="font-label-bold text-label-bold text-on-surface-variant uppercase tracking-wider">
                            Số điện thoại <span className="text-red-500">*</span>
                          </label>
                          <input
                            type="tel"
                            name="phone"
                            value={formData.phone}
                            onChange={handleInputChange}
                            className="w-full px-4 py-3 rounded-lg border border-outline-variant bg-surface font-body-lg transition-all focus:border-primary focus:ring-2 focus:ring-primary/10"
                            placeholder="Ví dụ: 090xxxxxxx"
                            required
                          />
                        </div>
                      </div>
                      <div className="mt-4 flex items-start gap-3">
                        <Info size={20} className="text-secondary flex-shrink-0 mt-0.5" />
                        <p className="font-body-sm text-on-secondary-fixed-variant">
                          Thông tin số điện thoại của bạn sẽ được công khai để người nhặt có thể liên hệ.
                        </p>
                      </div>
                    </div>
                  )}

                  {/* Found Mode Contact Info */}
                  {mode === 'found' && (
                    <div className="space-y-3">
                      <div className="flex flex-col gap-3">
                        <label className="flex items-center gap-3 p-4 rounded-xl border border-outline-variant bg-surface cursor-pointer hover:border-primary transition-all">
                          <input
                            type="radio"
                            name="visibility"
                            value="public"
                            checked={formData.visibility === 'public'}
                            onChange={handleInputChange}
                            className="w-5 h-5 text-primary"
                          />
                          <div>
                            <span className="font-body-lg font-bold block">Công khai</span>
                            <p className="font-body-sm text-on-surface-variant">
                              Ai cũng có thể thấy thông tin liên hệ của bạn.
                            </p>
                          </div>
                        </label>
                        <label className="flex items-center gap-3 p-4 rounded-xl border border-outline-variant bg-surface cursor-pointer hover:border-primary transition-all">
                          <input
                            type="radio"
                            name="visibility"
                            value="match"
                            checked={formData.visibility === 'match'}
                            onChange={handleInputChange}
                            className="w-5 h-5 text-primary"
                          />
                          <div>
                            <span className="font-body-lg font-bold block">Công khai khi có người xác nhận (Match)</span>
                            <p className="font-body-sm text-on-surface-variant">
                              Chỉ hiển thị thông tin khi bạn xác nhận yêu cầu nhận lại đồ là chính xác.
                            </p>
                          </div>
                        </label>
                      </div>
                    </div>
                  )}
                </div>
              )}

              {/* Action Button */}
              <div className="pt-6">
                <button
                  type="submit"
                  className="w-full bg-primary text-on-primary-container py-4 rounded-xl font-headline-md shadow-lg shadow-primary/20 hover:brightness-110 active:scale-95 transition-all flex items-center justify-center gap-2"
                >
                  {mode === 'found' ? 'Tiếp tục thiết lập câu hỏi' : 'Đăng tin ngay'}
                  <Send size={20} />
                </button>
                <p className="text-center font-body-sm text-on-surface-variant mt-4 px-8">
                  Bằng cách đăng tin, bạn đồng ý với{' '}
                  <Link to="/terms" className="text-primary underline hover:no-underline">
                    Điều khoản sử dụng
                  </Link>{' '}
                  của Sài Gòn Tìm Đồ.
                </p>
              </div>
            </>
          ) : (
            <div className="space-y-6 animate-fade-in">
              <div className="border-b border-outline-variant/30 pb-4 mb-4 text-left">
                <h2 className="font-headline-md text-primary mb-2 text-xl font-bold">Câu hỏi xác minh thông tin</h2>
                <p className="text-on-surface-variant font-body-md text-sm">
                  Để đảm bảo người nhận lại đồ là chính chủ, vui lòng thiết lập các câu hỏi xác minh dựa trên món đồ bạn nhặt được.
                </p>
              </div>

              {verificationsList.length === 0 ? (
                <div className="text-center py-8 bg-surface-container rounded-xl border border-dashed border-outline-variant">
                  <p className="text-on-surface-variant font-body-lg mb-4 text-sm">Chưa có câu hỏi xác minh nào được gợi ý.</p>
                  <button
                    type="button"
                    onClick={handleAddQuestion}
                    className="px-6 py-2.5 bg-primary text-white rounded-lg font-bold hover:opacity-90 transition-all text-sm"
                  >
                    + Tạo câu hỏi mới
                  </button>
                </div>
              ) : (
                <div className="space-y-4">
                  {verificationsList.map((q, index) => (
                    <div key={index} className="p-5 bg-surface-container rounded-xl border border-outline-variant/50 relative space-y-3 text-left">
                      <button
                        type="button"
                        onClick={() => handleRemoveQuestion(index)}
                        className="absolute top-4 right-4 text-red-500 hover:text-red-700 font-bold text-xs bg-red-50 hover:bg-red-100 px-2 py-1 rounded"
                        title="Xoá câu hỏi"
                      >
                        Xoá
                      </button>

                      <div className="space-y-1">
                        <label className="font-label-bold text-xs font-bold text-on-surface-variant uppercase tracking-wider block">
                          Câu hỏi {index + 1} <span className="text-red-500">*</span>
                        </label>
                        <input
                          type="text"
                          value={q.title}
                          onChange={(e) => handleQuestionChange(index, 'title', e.target.value)}
                          placeholder="Ví dụ: Balo có treo móc khóa hình gì?"
                          className="w-full px-4 py-2.5 rounded-lg border border-outline-variant bg-surface font-body-lg text-sm"
                          required
                        />
                      </div>

                      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div className="space-y-1">
                          <label className="font-label-bold text-xs font-bold text-on-surface-variant uppercase tracking-wider block">
                            Đáp án đúng <span className="text-red-500">*</span>
                          </label>
                          <input
                            type="text"
                            value={q.correctAnswer}
                            onChange={(e) => handleQuestionChange(index, 'correctAnswer', e.target.value)}
                            placeholder="Ví dụ: Hình gấu bông dâu tây màu hồng"
                            className="w-full px-4 py-2.5 rounded-lg border border-outline-variant bg-surface font-body-lg text-sm"
                            required
                          />
                        </div>

                        <div className="space-y-1">
                          <label className="font-label-bold text-xs font-bold text-on-surface-variant uppercase tracking-wider block">
                            Độ quan trọng (Bán kính tìm kiếm)
                          </label>
                          <select
                            value={q.importantPoint}
                            onChange={(e) => handleQuestionChange(index, 'importantPoint', e.target.value)}
                            className="w-full px-4 py-2.5 rounded-lg border border-outline-variant bg-surface font-body-lg text-sm cursor-pointer"
                          >
                            <option value="1">1 (Rất thấp)</option>
                            <option value="2">2 (Thấp)</option>
                            <option value="3">3 (Trung bình)</option>
                            <option value="4">4 (Quan trọng)</option>
                            <option value="5">5 (Rất quan trọng)</option>
                          </select>
                        </div>
                      </div>
                    </div>
                  ))}
                  
                  <button
                    type="button"
                    onClick={handleAddQuestion}
                    className="w-full py-3 border-2 border-dashed border-primary/30 rounded-xl text-primary font-bold hover:bg-primary/5 transition-all flex items-center justify-center gap-2 text-sm"
                  >
                    + Thêm câu hỏi khác
                  </button>
                </div>
              )}

              {/* Action Buttons */}
              <div className="pt-6 border-t border-outline-variant/30 flex gap-4">
                <button
                  type="button"
                  onClick={() => setCurrentStep(1)}
                  className="flex-1 py-4 border border-outline-variant rounded-xl font-headline-md hover:bg-surface-container text-sm font-semibold transition-all"
                >
                  Quay lại sửa tin
                </button>
                <button
                  type="submit"
                  className="flex-1 bg-primary text-white py-4 rounded-xl font-headline-md shadow-lg shadow-primary/20 hover:brightness-110 active:scale-95 transition-all flex items-center justify-center gap-2 text-sm font-bold"
                >
                  Hoàn tất & Đăng tin
                  <Send size={20} />
                </button>
              </div>
            </div>
          )}
        </form>
      </div>

      {/* Matches Modal Popup */}
      {isMatchesModalOpen && matchesList.length > 0 && (
        <div className="fixed inset-0 bg-black/60 backdrop-blur-sm z-[9999] flex items-center justify-center p-4 md:p-6 overflow-y-auto animate-fade-in">
          <div className="bg-surface rounded-2xl border border-outline-variant max-w-[800px] w-full max-h-[90vh] overflow-y-auto shadow-2xl p-6 md:p-8 flex flex-col justify-between space-y-6 relative text-left">
            
            {/* Modal Header */}
            <div className="border-b border-outline-variant/30 pb-4">
              <h2 className="font-headline-md text-primary mb-2 text-xl font-bold flex items-center gap-2">
                <span className="material-symbols-outlined text-primary text-[28px]">find_in_page</span>
                Bài đăng tương đồng tìm thấy
              </h2>
              <p className="text-on-surface-variant font-body-md text-sm">
                Hệ thống AI đã phát hiện một số tin đăng có đặc điểm tương đồng cao với bài viết của bạn. Vui lòng kiểm tra kỹ các bài viết dưới đây:
              </p>
            </div>

            {/* Modal Content */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 overflow-y-auto py-2">
              {matchesList.map((match) => {
                const details = fetchedMatchDetails[match.post_id];
                const imgUrl = match.image_url || details?.image_url || details?.image || details?.imageUrl || (details?.images ? details.images[0] : null) || "https://placehold.co/600x400?text=No+Image";
                const title = details?.title || `Bài viết #${match.post_id}`;
                const description = details?.description;
                const district = details?.location?.district || details?.district;

                return (
                  <div key={match.post_id} className="bg-surface-container rounded-xl overflow-hidden border border-outline-variant flex flex-row shadow-sm h-28">
                    {/* Left: Image (Wider width) */}
                    <div className="w-[35%] shrink-0 h-full relative bg-slate-100">
                      <img
                        src={imgUrl}
                        alt={title}
                        className="w-full h-full object-cover"
                      />
                    </div>

                    {/* Right: Info & Button */}
                    <div className="p-3 flex flex-col justify-between flex-grow min-w-0 text-left">
                      <div>
                        <h3 className="font-bold text-sm truncate text-on-surface mb-0.5">
                          {title}
                        </h3>
                        {description && (
                          <p className="text-[11px] text-on-surface-variant line-clamp-1">
                            {description}
                          </p>
                        )}
                        {district && district !== "Không rõ khu vực" && (
                          <div className="flex items-center gap-1 text-[11px] text-outline mt-0.5">
                            <span className="material-symbols-outlined text-[13px]">location_on</span>
                            <span>{district}</span>
                          </div>
                        )}
                      </div>

                      {/* Score & Link button */}
                      <div className="flex justify-between items-end mt-1">
                        <span className="text-[10px] font-bold text-primary">
                          Khớp: {match.human_score || `${(match.score * 100).toFixed(2)}%`}
                        </span>
                        <button
                          type="button"
                          onClick={() => setSelectedPostId(match.post_id)}
                          className="px-3 py-1 bg-primary text-on-primary rounded-lg font-bold hover:brightness-110 transition-all text-[10px] cursor-pointer"
                        >
                          Xem chi tiết
                        </button>
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>

            {/* Modal Action */}
            <div className="pt-4 border-t border-outline-variant/30 text-center">
              <button
                type="button"
                onClick={() => {
                  setIsMatchesModalOpen(false);
                  navigate('/');
                }}
                className="px-8 py-3 bg-secondary text-on-secondary rounded-xl font-bold hover:brightness-110 active:scale-95 transition-all text-sm shadow-md"
              >
                Hoàn tất & Quay về trang chủ
              </button>
            </div>
          </div>
        </div>
      )}
      {selectedPostId && (
        <PostDetailModal
          postId={selectedPostId}
          onClose={() => setSelectedPostId(null)}
        />
      )}
    </main>
  );
}
